export const TAOBAO_API = {
  ITEM: {
    ITEM_GET: "item_get",
    ITEM_GET_APP: "item_get_app",
    ITEM_GET_APP_PC: "item_get_app_pc",
    ITEM_GET_APP_PRO: "item_get_app_pro",
    ITEM_VIDEO: "item_video",
    ITEM_GET_PRO: "item_get_pro",
    ITEM_REVIEW: "item_review",
    ITEM_REVIEW_SHOW: "item_review_show",
    ITEM_VIDEO_BARRAGE: "item_video_barrage",
    ITEM_GET_DESC: "item_get_desc",
    ITEM_SYNC_ADD: "item_sync_add",
    ITEM_SYNC_GET: "item_sync_get",
    ITEM_GET_TITLE: "item_get_title",
    ITEM_LINK: "item_link",
    ITEM_GET_SALES: "item_get_sales",
    ITEM_SKU: "item_sku",
    ITEM_FEE: "item_fee",
    ITEM_PASSWORD: "item_password",
    ITEM_PASSWORD_VIP: "item_password_vip",
    ITEM_CAT_GET: "item_cat_get",
    ITEM_LIST_WEIGHT: "item_list_weight",
    ITEM_HISTORY_PRICE: "item_history_price",
    ITEM_LIST_UPDOWN: "item_list_updown",
    ITEM_SEARCH: "item_search",
    ITEM_SEARCH_TMALL: "item_search_tmall",
    ITEM_SEARCH_JNPITER: "item_search_jnpiter",
    ITEM_SEARCH_PRO: "item_search_pro",
    ITEM_SEARCH_IMG: "item_search_img",
    ITEM_SEARCH_SHOP: "item_search_shop",
    ITEM_SEARCH_SELLER: "item_search_seller",
    ITEM_SEARCH_GUANG: "item_search_guang",
    ITEM_SEARCH_SUGGEST: "item_search_suggest",
    ITEM_SEARCH_JUPAGE: "item_search_jupage",
    ITEM_SEARCH_COUPON: "item_search_coupon",
    ITEM_SEARCH_SAMESTYLE: "item_search_samestyle",
    ITEM_SEARCH_SIMILAR: "item_search_similar",
    ITEM_SEARCH_NEIGHBORS: "item_search_neighbors",
    ITEM_RECOMMEND: "item_recommend",
    ITEM_VIDEOLIST: "item_videolist",
    ITEM_VIDEOLIST_CAT: "item_videolist_cat",
    ITEM_SEARCH_BEST: "item_search_best",
    ITEM_SEARCH_CAT: "item_search_cat",
    ITEM_QUESTION_ANSWER: "item_question_answer",
    ITEM_QUESTION_ANSWER_INFO: "item_question_answer_info",
    ITEM_HALF: "item_half",
    ITEM_SEARCH_LIMIT: "item_search_limit",
    ITEM_SEARCH_SHOP_SELLERID: "item_search_shop_sellerid",
  },

  CATEGORY: {
    CAT_GET: "cat_get",
    CAT_GET_APP: "cat_get_app",
  },

  SELLER: {
    SELLER_INFO: "seller_info",
    SHOP_INFO_APP: "shop_info_app",
    GET_SELLER_ID: "get_seller_id",
    SELLER_ORDER_LIST: "seller_order_list",
    SELLER_ORDER_DETAIL: "seller_order_detail",
    SELLER_ORDER_ADDRESS: "seller_order_address",
    SELLER_ORDER_CLOSE: "seller_order_close",
    SELLER_ORDER_MESSAGE: "seller_order_message",
    SELLER_ORDER_SEND: "seller_order_send",
    SELLER_DELIVERY_TPL_LIST: "seller_delivery_tpl_list",
    SELLER_DELIVERY_TPL_ADD: "seller_delivery_tpl_add",
    SELLER_DELIVERY_TPL_COPY: "seller_delivery_tpl_copy",
    SELLER_DELIVERY_TPL_MODIFY: "seller_delivery_tpl_modify",
    SELLER_DELIVERY_TPL_DEL: "seller_delivery_tpl_del",
    SELLER_AUCTION_LIST: "seller_auction_list",
    SELLER_AUCTION: "seller_auction",
    SELLER_ITEM_ADD: "seller_item_add",
    SELLER_IMG_LIST: "seller_img_list",
    SELLER_IMG_ADD: "seller_img_add",
    SELLER_IMG_DEL: "seller_img_del",
    SELLER_IMG_DIR_LIST: "seller_img_dir_list",
    SELLER_IMG_DIR_ADD: "seller_img_dir_add",
    SELLER_IMG_DIR_DEL: "seller_img_dir_del",
    SELLER_CAT_PROPS: "seller_cat_props",
  },

  BUYER: {
    BUYER_CART_ADD: "buyer_cart_add",
    BUYER_CART_ADD_APP: "buyer_cart_add_app",
    BUYER_CART_REMOVE: "buyer_cart_remove",
    BUYER_CART_CLEAR: "buyer_cart_clear",
    BUYER_CART_LIST: "buyer_cart_list",
    BUYER_CART_ORDER: "buyer_cart_order",
    BUYER_ORDER_LIST: "buyer_order_list",
    BUYER_ORDER_LIST_APP: "buyer_order_list_app",
    BUYER_ORDER_DETAIL_APP: "buyer_order_detail_app",
    BUYER_ORDER_DETAIL: "buyer_order_detail",
    BUYER_ORDER_EXPRESS: "buyer_order_express",
    BUYER_ORDER_MESSAGE: "buyer_order_message",
    BUYER_ADDRESS_LIST: "buyer_address_list",
    BUYER_ADDRESS_CLEAR: "buyer_address_clear",
    BUYER_ADDRESS_REMOVE: "buyer_address_remove",
    BUYER_ADDRESS_MODIFY: "buyer_address_modify",
    BUYER_ADDRESS_ADD: "buyer_address_add",
    BUYER_FOOTMARK_LIST: "buyer_footmark_list",
    BUYER_FAVORITE_LIST: "buyer_favorite_list",
    BUYER_FAVORITE_SHOP_LIST: "buyer_favorite_shop_list",
    BUYER_INFO: "buyer_info",
    BUYER_TOKEN: "buyer_token",
    BUYER_TOKEN_CHECK: "buyer_token_check",
    BUYER_TOKEN_CREATE: "buyer_token_create",
    BUYER_TOKEN_QRCODE: "buyer_token_qrcode",
    BUYER_TOKEN_QRCODE_CK: "buyer_token_qrcode_ck",
  },

  BRAND: {
    BRAND_CAT: "brand_cat",
    BRAND_CAT_TOP: "brand_cat_top",
    BRAND_CAT_LIST: "brand_cat_list",
    BRAND_KEYWORD_LIST: "brand_keyword_list",
    BRAND_INFO: "brand_info",
    BRAND_PRODUCT_LIST: "brand_product_list",
  },

  UTILS: {
    TBK_ORDER_QUERY: "tbk_order_query",
    UPLOAD_IMG: "upload_img",
    IMG2TEXT: "img2text",
    UPLOAD_IMG_VIP: "upload_img_vip",
    CUSTOM: "custom",
    PRODUCT_ADD: "product_add",
  },
};
